name: Aman
on:
  push:
    branches:
      - main  

jobs:
  build: 
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   

      - name: Build && Deploy new version
        run: echo "Running tests"   # 
