name: Deploy HTML File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create public directory and copy files
        run: |
          mkdir -p public   # Create the public directory
          cp -R * public/   # Copy all files to the public directory
