name: Deploy HTML File

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy HTML File
        run: |
          # Optionally create a deployment directory if needed, remove this if not necessary
          mkdir -p public 
          cp *.html public/  # Copy only HTML files to public directory
